#!/bin/bash

# update electrumx banner to report bitcoin memory pool, fees, height and time since last block
# activate with cron job similar to this
#*/2 * * * *  ~/bin/update-electrumx-banner

# specify your bitcoin-cli location
BITCOIN_CLI=/usr/bin/bitcoin-cli

# specify your bitcoin data directory
BITCOIN_DATADIR=~/.bitcoin

# specify the location of your electrumx banner file
# note: uses %{BANNER}.template as the template (top portion) of each banner update
BANNER=~/.electrumx/banner

# save initial banner as template for creation of new banners
if [ ! -f ${BANNER}.template ]; then
	cp ${BANNER} ${BANNER}.template
fi

# create new banner from template
cp ${BANNER}.template ${BANNER}.new

# timestamp
printf "As of %s " "$(date -u)" >> ${BANNER}.new

# mempool
MEMPOOL=`${BITCOIN_CLI} -datadir=${BITCOIN_DATADIR} getmempoolinfo | grep size | grep -o '[0-9\.]*'`
printf "there are %'d transactions in the memory pool\n" ${MEMPOOL} >> ${BANNER}.new

# report last block and current height from electrumx journal
TFILE=/tmp/btcfees-$$
journalctl --since "6 hours ago" -u electrumx -o short-iso --utc | grep Prefetcher:new | tail -n 1 > ${TFILE}
if [ `wc -c < ${TFILE}` -gt 10 ]; then
	block_height=`< ${TFILE} awk '{print $7}'`
	block_time=`< ${TFILE} awk '{print $1}'`
	block_utime=`date -ud $block_time +'%s'`
	now_utime=`date +'%s'`
	minutes_ago=`echo ${now_utime} ${block_utime} | awk '{print int(($1-$2)/6)/10}'`
	echo "Last block: ${minutes_ago} minutes ago; current height: ${block_height}" >> ${BANNER}.new
fi
rm ${TFILE}

# get exchange rate and average fee per satoshi
if ${BITCOIN_CLI} --version | grep -q ABC; then
        USDPERBTC=`curl -m 10 -L -s 'https://apiv2.bitcoinaverage.com/indices/global/ticker/BCHUSD' | python3 -c 'import sys, json; j=json.load(sys.stdin); print(j["last"])'`
        TICKER=BCH
		BYTESPERTX=226
else
        USDPERBTC=`curl -m 10 -L -s 'https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCUSD' | python3 -c 'import sys, json; j=json.load(sys.stdin); print(j["last"])'`
        TICKER=BTC
		BYTESPERTX=168
fi
USDPERSAT=`echo ${USDPERBTC} | awk '{print $1/100000000}'`

echo "Current exchange rate = ${USDPERBTC} USD/${TICKER}; typical TX size = ${BYTESPERTX} bytes" >> ${BANNER}.new

# report fees for various block times
for BLOCKS in 2 6 12 24 144 504 1008
do
        SATPERBYTE=`${BITCOIN_CLI} -datadir=${BITCOIN_DATADIR} estimatesmartfee ${BLOCKS} | grep feerate  | grep -o '[0-9\.\-]*' | awk '{print $1*100000+0.5}'`
        if [ `echo ${SATPERBYTE} | awk '{print int($1)}'` -lt 1 ]; then
                break;
        fi
        echo ${BLOCKS} ${SATPERBYTE} ${BYTESPERTX} ${USDPERSAT} | awk '{printf "Estimated miner fee for confirmation in %d blocks (%s hours) = %d sat/B (%d sat or $%0.2f)\n", $1, int($1/0.06)/100, $2, $2*$3, $2*$3*$4 }' >> ${BANNER}.new
done

# save backup of original banner on first run (just in case...)
if [ ! -f ${BANNER}.backup ]; then
	cp ${BANNER} ${BANNER}.backup
fi

# replace banner with newly generated version
mv ${BANNER}.new ${BANNER}
